({
  baseUrl: ".",
  name: "node_modules/almond/almond.js",
  paths: {
    "ace": "ace/lib/ace",
    "highlight": "build/app"
  },
  include: [
    "highlight",
    "ace/theme/gob",
    "ace/theme/twilight",
    "ace/theme/tomorrow_night_bright",
    "ace/theme/nord_dark",
    "ace/theme/dracula",
    "ace/theme/sqlserver",
    "ace/theme/dawn",
    "ace/theme/pastel_on_dark",
    "ace/theme/vibrant_ink",
    "ace/theme/solarized_dark",
    "ace/theme/tomorrow_night",
    "ace/theme/katzenmilch",
    "ace/theme/crimson_editor",
    "ace/theme/ambiance",
    "ace/theme/tomorrow_night_eighties",
    "ace/theme/chrome",
    "ace/theme/solarized_light",
    "ace/theme/kuroir",
    "ace/theme/terminal",
    "ace/theme/idle_fingers",
    "ace/theme/dreamweaver",
    "ace/theme/textmate",
    "ace/theme/tomorrow",
    "ace/theme/merbivore",
    "ace/theme/mono_industrial",
    "ace/theme/monokai",
    "ace/theme/iplastic",
    "ace/theme/tomorrow_night_blue",
    "ace/theme/gruvbox",
    "ace/theme/cobalt",
    "ace/theme/chaos",
    "ace/theme/github",
    "ace/theme/eclipse",
    "ace/theme/xcode",
    "ace/theme/kr_theme",
    "ace/theme/clouds",
    "ace/theme/merbivore_soft",
    "ace/theme/clouds_midnight"
  ],
  optimize: "uglify",
  out: "inst/js/app.js"
})
